# Generated by Django 3.1.4 on 2022-03-23 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Regiony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_med',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Nazwisko')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Imiona')),
                ('pesel', models.CharField(max_length=11, null=True, unique=True, verbose_name='Pesel')),
                ('date_brith', models.DateField(verbose_name='Data Urodzenia')),
                ('npwz', models.CharField(max_length=8, unique=True, verbose_name='Numer prawa wykonywania zawodu')),
                ('phone', models.CharField(max_length=9, null=True, unique=True, verbose_name='Numer telefonu')),
                ('regional_city', models.CharField(max_length=200, null=True, verbose_name='Miasto')),
                ('str_name', models.CharField(max_length=20, null=True, verbose_name='Ulica')),
                ('str_number', models.CharField(max_length=4, null=True, verbose_name='Numer domu')),
                ('str_number_one', models.CharField(max_length=4, null=True, verbose_name='Numer mieszkania(opcjonalnie)')),
                ('Register_date', models.DateField(default=django.utils.timezone.now)),
                ('groupadd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Grupa')),
                ('iduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('regional_woj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Regiony.regional')),
            ],
            options={
                'verbose_name_plural': 'Personel',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Nazwisko')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Imiona')),
                ('date_brith', models.DateField(verbose_name='Data Urodzenia')),
                ('pesel', models.CharField(max_length=11, null=True, unique=True, verbose_name='Pesel')),
                ('peselN', models.CharField(choices=[('0', 'TAK'), ('1', 'NIE')], default=0, max_length=11, null=True, verbose_name='Brak peselu')),
                ('IDname', models.CharField(choices=[('0', 'Brak'), ('1', 'EKUZ'), ('2', 'Dowód osobisty'), ('3', 'Paszport')], max_length=100, null=True, verbose_name='Nazwa dokumentu')),
                ('IDnumber', models.CharField(max_length=20, null=True, unique=True, verbose_name='Numer dokumentu')),
                ('phone', models.CharField(max_length=9, null=True, unique=True, verbose_name='Numer telefonu')),
                ('regional_city', models.CharField(max_length=200, null=True, verbose_name='Miasto')),
                ('post', models.CharField(default=0, max_length=100, verbose_name='Kod Pocztowy')),
                ('str_name', models.CharField(max_length=20, verbose_name='Ulica')),
                ('str_number', models.CharField(max_length=4, verbose_name='Numer domu')),
                ('str_number_one', models.CharField(max_length=4, verbose_name='Numer mieszkania(opcjonalnie)')),
                ('doc', models.FileField(upload_to='', verbose_name='Skan dowodu')),
                ('check', models.BooleanField(default=False, verbose_name='Potwierdzenie konta')),
                ('Register_date', models.DateField(default=django.utils.timezone.now)),
                ('iduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('regional_woj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Regiony.regional', verbose_name='Województwo')),
            ],
            options={
                'verbose_name_plural': 'Pacjenci',
            },
        ),
    ]
