# Generated by Django 3.1.4 on 2022-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='IDnumber',
            field=models.CharField(max_length=20, null=True, verbose_name='Numer dokumentu'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='pesel',
            field=models.CharField(max_length=11, verbose_name='Pesel'),
        ),
    ]
