# Generated by Django 3.1.4 on 2022-03-23 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reg', models.CharField(max_length=50, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name_plural': 'Województwa',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('id_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Regiony.regional')),
            ],
            options={
                'verbose_name_plural': 'Miasta',
            },
        ),
    ]
