# Generated by Django 3.1.4 on 2022-03-23 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Nazwa')),
                ('doc', models.FileField(blank=True, null=True, upload_to='', verbose_name='Załącznik')),
            ],
            options={
                'verbose_name_plural': 'Dokumenty',
            },
        ),
        migrations.CreateModel(
            name='Form_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nazwa Formularza do pobrania')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fromularz do pobrania')),
            ],
            options={
                'verbose_name_plural': 'Formularze',
            },
        ),
        migrations.CreateModel(
            name='Form_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nazwa przsłanego Formularza ')),
                ('type_forms', models.CharField(choices=[('0', 'Deklaracja do Lekarza'), ('1', 'Deklaracja do Pielęgniarki środowiskowej'), ('2', 'Deklaracja do Położnej'), ('3', 'Formularz zdrowotny COVID')], max_length=100, null=True, verbose_name='Rodzaj Formularza')),
                ('status', models.CharField(choices=[('0', 'Przesłany'), ('1', 'W trakcie weryfikacji'), ('2', 'Zakceptowany'), ('2', 'Niezakceptowany')], default=0, max_length=100, null=True, verbose_name='Status dokumentu')),
                ('remarks_user', models.TextField(null=True, verbose_name='Uwagi użytkownika')),
                ('remarks_person', models.TextField(null=True, verbose_name='Uwagi Pracownika placówki')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data przesłania')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fromularz do pobrania')),
            ],
            options={
                'verbose_name_plural': 'Formularze przesłane przez użytkownika',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateregister', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(verbose_name='Opis')),
                ('confirmation', models.CharField(choices=[('0', 'Niepotwierdzony'), ('1', 'Potwierdzony')], default='0', max_length=100, verbose_name='Potwierdzenie wizyty')),
                ('type_visit', models.CharField(choices=[('0', 'Receptowa'), ('1', 'Porada'), ('2', 'Teleporada'), ('3', 'Z skierowaniem'), ('4', 'Kontynuacja')], default='1', max_length=100, verbose_name='Rodzajy Wizyty')),
            ],
            options={
                'verbose_name_plural': 'Wizyty',
            },
        ),
    ]
