# Generated by Django 3.1.4 on 2022-03-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pacjent', '0001_initial'),
        ('Placowki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Placowki.organization', verbose_name='Komórka Organizacyjna'),
        ),
    ]
