# Generated by Django 3.1.4 on 2022-03-23 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('Placowki', '0001_initial'),
        ('Terminarz', '0001_initial'),
        ('Pacjent', '0002_visit_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='patient_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Profile.personal'),
        ),
        migrations.AddField(
            model_name='visit',
            name='patient_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='struct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Placowki.struct_organization', verbose_name='Zakład leczniczy'),
        ),
        migrations.AddField(
            model_name='visit',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Terminarz.term_day', verbose_name='Termin '),
        ),
        migrations.AddField(
            model_name='visit',
            name='unity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Placowki.unit', verbose_name='Jednostka '),
        ),
        migrations.AddField(
            model_name='form_user',
            name='name_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Placowki.unit', verbose_name='Jednostka'),
        ),
        migrations.AddField(
            model_name='form_user',
            name='patient_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Profile.personal', verbose_name='Pacjent'),
        ),
        migrations.AddField(
            model_name='document',
            name='author_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Profile.personal', verbose_name='Pacjent'),
        ),
        migrations.AddField(
            model_name='document',
            name='author_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
