# Generated by Django 3.1.4 on 2022-03-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacjent', '0004_auto_20220323_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='description_person',
            field=models.TextField(null=True, verbose_name='Opis lekarza'),
        ),
        migrations.AddField(
            model_name='visit',
            name='dodatkowe',
            field=models.TextField(null=True, verbose_name='Recepty i skierowania'),
        ),
        migrations.AddField(
            model_name='visit',
            name='key',
            field=models.CharField(max_length=4, null=True, verbose_name='Kod e-skierowania'),
        ),
        migrations.AddField(
            model_name='visit',
            name='rozone',
            field=models.CharField(max_length=100, null=True, verbose_name='Rozpoznanie główne'),
        ),
    ]
