# Generated by Django 3.1.4 on 2022-03-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacjent', '0005_auto_20220324_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='confirmation',
            field=models.CharField(choices=[('0', 'Niepotwierdzony'), ('1', 'Potwierdzony')], default='0', max_length=100, null=True, verbose_name='Potwierdzenie wizyty'),
        ),
    ]
