# Generated by Django 3.1.4 on 2022-03-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20220327_1402'),
        ('Terminarz', '0002_auto_20220329_1106'),
        ('Pacjent', '0006_auto_20220324_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='dodatkowe',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='rozone',
        ),
        migrations.AlterField(
            model_name='visit',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Terminarz.term_day', verbose_name='Data Wizyty '),
        ),
        migrations.CreateModel(
            name='e_system_SKIEROWANIA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_e', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Kod skierowania')),
                ('iddoc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profile.personal_med', verbose_name='Lekarz')),
                ('idpac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profile.personal', verbose_name='Pacjents')),
                ('idvisit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pacjent.visit', verbose_name='Wizyta')),
            ],
            options={
                'verbose_name_plural': 'Skierowania',
            },
        ),
        migrations.CreateModel(
            name='e_system_RECEPTY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_e', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Kod Recepty')),
                ('iddoc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profile.personal_med', verbose_name='Lekarz')),
                ('idpac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profile.personal', verbose_name='Pacjents')),
                ('idvisit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pacjent.visit', verbose_name='Wizyta')),
            ],
            options={
                'verbose_name_plural': 'Recepty',
            },
        ),
    ]
