# Generated by Django 3.1.4 on 2022-03-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slowniki', '0002_icd10'),
        ('Pacjent', '0007_auto_20220329_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='id10',
            field=models.ManyToManyField(null=True, to='Slowniki.ICD10', verbose_name='Rozpoznania'),
        ),
    ]
