# Generated by Django 3.1.4 on 2022-03-29 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Terminarz', '0002_auto_20220329_1106'),
        ('Pacjent', '0010_auto_20220329_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('0', 'Zarejestrowana'), ('1', 'Zapalnowana'), ('2', 'Do realizacji'), ('3', 'Zrealizowana'), ('4', 'Odwołana')], default='0', max_length=100, null=True, verbose_name='Status aktualny'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Terminarz.term_day', unique=True, verbose_name='Data Wizyty '),
        ),
    ]
