# Generated by Django 3.1.4 on 2022-03-29 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20220327_1402'),
        ('Placowki', '0003_auto_20220326_2346'),
        ('Pacjent', '0011_auto_20220329_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='dekl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.personal_med', unique=True, verbose_name='Lekarz')),
                ('idfield', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pacjent.form_user', unique=True, verbose_name='Formularz')),
                ('idpac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.personal', unique=True, verbose_name='Pacjent')),
                ('idunit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Placowki.unit', unique=True, verbose_name='Jednostka')),
            ],
            options={
                'verbose_name_plural': 'Deklaracje',
            },
        ),
    ]
