# Generated by Django 3.1.4 on 2022-03-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacjent', '0012_dekl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nazwa przesłanego Formularza '),
        ),
    ]
