# Generated by Django 3.1.4 on 2022-04-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20220327_1402'),
        ('Pacjent', '0014_auto_20220405_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dekl',
            name='iddoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.personal_med', unique=True, verbose_name='Lekarz'),
        ),
    ]
