# Generated by Django 3.1.4 on 2022-03-29 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Terminarz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='work_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Data generacji'),
        ),
    ]
