# Generated by Django 3.1.4 on 2022-03-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICD9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=10, null=True, unique=True, verbose_name='Kod')),
                ('nazwa', models.CharField(max_length=200, null=True, unique=True, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name_plural': 'Słownik ICD9',
            },
        ),
    ]
