# Generated by Django 3.1.4 on 2022-03-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Regiony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
            ],
            options={
                'verbose_name_plural': 'Jednostki i lekarze',
            },
        ),
        migrations.CreateModel(
            name='NFZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True, verbose_name='Oddział NFZ')),
                ('regional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Regiony.regional', verbose_name='Województwo')),
            ],
            options={
                'verbose_name_plural': 'Oddział NFZ',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True, verbose_name='Nazwa Podmiot Leczniczy')),
                ('nip', models.CharField(max_length=10, null=True, unique=True, verbose_name='Nip podmiotu leczniczego')),
                ('regon', models.CharField(max_length=9, null=True, unique=True, verbose_name='Regon podmiotu leczniczego')),
                ('krs', models.CharField(max_length=25, null=True, unique=True, verbose_name='KRS podmiotu leczniczego')),
                ('number_resort', models.CharField(max_length=25, null=True, unique=True, verbose_name='Numer księgi resortowej')),
                ('number_swiat', models.CharField(max_length=25, null=True, unique=True, verbose_name='Numer świadczniobiorcy')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('oddz_nfz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Placowki.nfz', verbose_name='Oddział NFZ')),
            ],
            options={
                'verbose_name_plural': 'Podmiot Leczniczy',
            },
        ),
        migrations.CreateModel(
            name='Struct_Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Nazwa strukty organizacyjnej')),
                ('city', models.CharField(max_length=200, null=True, verbose_name='Miasto')),
                ('adress1', models.CharField(max_length=100, null=True, verbose_name='Ulica')),
                ('adress2', models.CharField(max_length=5, null=True, verbose_name='Numer domu')),
                ('adress3', models.CharField(max_length=5, null=True, verbose_name='Numer mieszkania')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Telefon')),
                ('mail', models.EmailField(max_length=100, null=True, verbose_name='E-mail')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('type_place', models.CharField(choices=[('0', 'Poradnia ogólna'), ('1', 'Poradnia Specjalistyczna'), ('2', 'Szpitale')], max_length=200, null=True, verbose_name='Typ Placówki')),
                ('dekl', models.CharField(choices=[('0', 'TAK'), ('1', 'NIE')], max_length=200, null=True, verbose_name='Czy wymagana delaracja ')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Placowki.organization', verbose_name='Podmiot leczniczy')),
            ],
            options={
                'verbose_name_plural': 'Zakład leczniczy',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Nazwa jednostki')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Placowki.struct_organization', verbose_name='Zakład leczniczy')),
            ],
            options={
                'verbose_name_plural': 'Jednostka',
            },
        ),
    ]
