# Generated by Django 3.1.4 on 2022-03-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('Placowki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Profile.personal_med'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Placowki.unit'),
        ),
    ]
