# Generated by Django 3.1.4 on 2022-03-26 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Placowki', '0002_auto_20220323_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nazwa Podmiot Leczniczy'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='number_swiat',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='Numer świadczniodawcy'),
        ),
        migrations.AlterField(
            model_name='struct_organization',
            name='adress1',
            field=models.CharField(max_length=100, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='struct_organization',
            name='adress2',
            field=models.CharField(max_length=5, verbose_name='Numer domu'),
        ),
        migrations.AlterField(
            model_name='struct_organization',
            name='adress3',
            field=models.CharField(max_length=5, verbose_name='Numer mieszkania'),
        ),
        migrations.AlterField(
            model_name='struct_organization',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='struct_organization',
            name='dekl',
            field=models.CharField(choices=[('0', 'TAK'), ('1', 'NIE')], max_length=200, verbose_name='Czy wymagana delaracja '),
        ),
        migrations.AlterField(
            model_name='struct_organization',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='struct_organization',
            name='mail',
            field=models.EmailField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='struct_organization',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa strukty organizacyjnej'),
        ),
        migrations.AlterField(
            model_name='struct_organization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Placowki.organization', verbose_name='Podmiot leczniczy'),
        ),
        migrations.AlterField(
            model_name='struct_organization',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='struct_organization',
            name='type_place',
            field=models.CharField(choices=[('0', 'Poradnia ogólna'), ('1', 'Poradnia Specjalistyczna'), ('2', 'Szpitale')], max_length=200, verbose_name='Typ Placówki'),
        ),
    ]
