# Generated by Django 3.1.4 on 2022-04-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Placowki', '0003_auto_20220326_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Jednostki i Personel'},
        ),
    ]
