# Generated by Django 3.1.4 on 2022-04-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20220327_1402'),
        ('Placowki', '0004_auto_20220401_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profile.personal_med'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Placowki.unit'),
        ),
    ]
